### ISSUE TITLE
Difficulties with receiving JavaScript notifications from the player

### ISSUE THREAD

**Issue by GD14** [ispringsolutions/Player-SDK#2]
Hello！ I try  to create a simple html  under your player-sdk-intro.md. However I find  this function,which you said will be invoked by the presentation when the player is  initialized,isn't invoked at all. And I try to check your http-samples. I find the function in both presentation_control and presentation_event_listening projects can't be invoked. So,I have to ask for help from you. why the sample can't be performed really confused me.

        ispringPresentationConnector.register = function(player)
        {
            // This function will be invoked by the presentation when the player is initialized
        };

**Comment by alexey-malov** [comment]
Adobe Flahs Player does not allow local SWF files to perform any network activity such as communicating with JavaScript. In other words, Flash presentations can send notifications and receive commands only when they are loaded under http: or https protocol. In the internet they should work without problems.

You can enable network access for local Flash files on your web site using Flash Player Security Settings.

![flash-player-security](https://cloud.githubusercontent.com/assets/6040682/16761509/196db970-4829-11e6-9467-9357b0d44401.png)

Google Chrome browser uses its own Flash Player plugin (called Pepper Flash).
For Chrome browser, you can edit trusted location settings here:
https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager04.html

**Comment by alexey-malov** [comment]
@GD14, please also make sure that you used iSpring Suite DX or iSpring Platform to generate the presentation.

In case the problem still exists, please attach some files that we can use to reproduce the problem, or give a link to your github account.

**Comment by GD14** [comment]
@alexey-malov, Thank you very much！ When I enabled network access for local Flash files,those samples can work well！ I did't know that the Adobe Flahs Player does not allow local SWF files to perform  network activities before.Thank you agagin for answering my questions so quickly.
