### ISSUE TITLE
Is there a way to get quizz results from the player API ?

### ISSUE THREAD

**Issue by RodolpheGohard** [ispringsolutions/Player-SDK#3]

**Comment by rodneytamblyn** [comment]
+1, either client side or via LTI, xAPI etc

**Comment by bonpapajosie** [comment]
hello, 
the code is not working on chrome

and i want to add thumbnail if possible

**Comment by alexey-malov** [comment]
Quiz player does not have a public API at the moment.

**Comment by StanAngeloff** [comment]
Do you intend on shipping an SDK for iSpring QuizMaker? It's currently a black box.

Are there any workarounds to at least grab a reference to the "controller" object driving the quiz?
