### ISSUE TITLE
gotoNextStep() is running wrong

### ISSUE THREAD

**Issue by deplop** [ispringsolutions/Player-SDK#4]
I have 9 steps in a slide and I even print out in console each step's duration.
But when I use gotoNextStep()  it run the first step by click as usual and then run all other steps automatically. This happens in many slide of mine though there are slides it works correctly (running a step then pause until click to run the next step)
This happens for the slides containing only 2 steps also. 
Btw, gotoPreviousStep() function works correctly.

**Comment by alexey-malov** [comment]
Could you please give a link to your sample?

**Comment by alexey-malov** [comment]
@deplop, I am closing this issue due to lack of details
