### ISSUE TITLE
DOMException about autoplay

### ISSUE THREAD

**Issue by Glioburd** [ispringsolutions/Player-SDK#8]
Hello, for now I'm just reproducing your exemples, with a converted powerpoint to html with Ispring Suite DX 9.7.8.24105, used in a iframe.

I cannot do anything because of a DOMException :

On chrome : 
> DOMException: DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD player.js?4108964B:195

On Firefox : 
> DOMException: "The play method is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

This _play_ method is called in the Index.html of the generated powerpoint.

I tried with a `allow="autoplay"` attribute in the iframe tag, and/or with `muted="muted"`. Still got the Exception.

Edit : allright, although there is no backend stuff in this, it works if I run the page from a built-in PHP server. If I run directly my index.html in the browser, it won't work.

**Comment by alexey-malov** [comment]
This exception is a result of media auto start availability checking. If media auto start is not allowed, an exception is thrown. This exception is logged in browser console only and does not prevent correct player functioning.
